//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Finance
    {
        public int FinanceId { get; set; }
        public System.DateTime FinanceDate { get; set; }
        public decimal Amount { get; set; }
        public string Desc { get; set; }
        public string Type { get; set; }
        public Nullable<int> Client { get; set; }
        public string IncomeOrExpense { get; set; }
    
        public virtual Client Client1 { get; set; }
    }
}
